import type { Metadata } from "next";
import "./globals.css";
import { Martian_Mono } from "next/font/google";

const martian = Martian_Mono({
  variable: "--font-martian",
  axes: ["wdth"],
  adjustFontFallback: false,
  fallback: ["monospace"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={martian.variable}>{children}</body>
    </html>
  );
}
